// data.js is the source of truth. This emits the same content for every native target.
// node scripts/gen.mjs   (data.test.mjs fails if outputs are stale)
import { writeFileSync } from 'node:fs';
globalThis.window = {};
await import('../data.js');
const F = globalThis.window.FIELDS;
const sw = s => JSON.stringify(s);
const kt = s => JSON.stringify(s).replace(/\$/g, '\\$');

writeFileSync('fields.json', JSON.stringify(F, null, 1));

writeFileSync('ios/Fieldbook/Fields.swift', `// Generated by scripts/gen.mjs from data.js. Do not edit.
import Foundation

struct Field: Identifiable, Hashable {
    let domain: String, name: String, studies: String, body: String, ideas: [String], gap: String
    var id: String { name }
}

let allFields: [Field] = [
${F.map(f => `    Field(domain: ${sw(f.d)}, name: ${sw(f.n)}, studies: ${sw(f.s)}, body: ${sw(f.p)}, ideas: [${f.k.map(sw).join(', ')}], gap: ${sw(f.g)}),`).join('\n')}
]
`);

writeFileSync('kmp/shared/src/commonMain/kotlin/com/nulljosh/fieldbook/Fields.kt', `// Generated by scripts/gen.mjs from data.js. Do not edit.
package com.nulljosh.fieldbook

data class Field(val domain: String, val name: String, val studies: String, val body: String, val ideas: List<String>, val gap: String)

val allFields: List<Field> = listOf(
${F.map(f => `    Field(${kt(f.d)}, ${kt(f.n)}, ${kt(f.s)}, ${kt(f.p)}, listOf(${f.k.map(kt).join(', ')}), ${kt(f.g)}),`).join('\n')}
)
`);
console.log(`generated ${F.length} fields`);
