# One-off: added the curated r: [] links to data.js on 2026-09-06. Kept so the map can be re-audited.
import re
L = {
"Classical mechanics": ["Calculus","Thermodynamics","Fluid dynamics","Relativity","Engineering","Differential equations and dynamics","Astrophysics and cosmology"],
"Thermodynamics": ["Physical chemistry","Information theory","Condensed matter physics","Meteorology","Nutrition","Engineering"],
"Electromagnetism": ["Optics","Relativity","Particle physics","Condensed matter physics","Acoustics"],
"Relativity": ["Astrophysics and cosmology","Quantum mechanics","Geometry and trigonometry","Astronomy"],
"Quantum mechanics": ["Particle physics","Condensed matter physics","Physical chemistry","General chemistry","Linear algebra","Probability","Nuclear physics","Optics"],
"Particle physics": ["Nuclear physics","Astrophysics and cosmology","Linear algebra"],
"Optics": ["Astronomy","Analytical chemistry","Geometry and trigonometry"],
"Acoustics": ["Differential equations and dynamics","Linguistics","Fluid dynamics"],
"Nuclear physics": ["Geology","Astrophysics and cosmology","Medicine"],
"Condensed matter physics": ["Materials science","Computer science","Inorganic chemistry"],
"Fluid dynamics": ["Meteorology","Oceanography","Cardiovascular system","Respiratory system","Engineering"],
"Astrophysics and cosmology": ["Astronomy","Planetary science","Thermodynamics"],
"General chemistry": ["Organic chemistry","Inorganic chemistry","Physical chemistry","Analytical chemistry","Biochemistry","Materials science","Arithmetic and number theory"],
"Organic chemistry": ["Biochemistry","Medicine","Nutrition","Agriculture"],
"Inorganic chemistry": ["Materials science","Geology","Biochemistry"],
"Physical chemistry": ["Biochemistry","Analytical chemistry","Differential equations and dynamics"],
"Biochemistry": ["Cell biology","Molecular biology","Nutrition","Digestive system","Endocrine system","Genetics"],
"Analytical chemistry": ["Medicine","Epidemiology and public health","Statistics"],
"Materials science": ["Engineering","Agriculture"],
"Cell biology": ["Molecular biology","Genetics","Microbiology","Developmental biology","Immunology","Homeostasis","Evolutionary biology"],
"Genetics": ["Molecular biology","Evolutionary biology","Developmental biology","Probability","Medicine","Agriculture","Reproductive system"],
"Molecular biology": ["Immunology","Microbiology","Artificial intelligence","Developmental biology"],
"Evolutionary biology": ["Ecology","Zoology","Botany","Microbiology","Anthropology","Psychology","Immunology","Statistics","Geology"],
"Ecology": ["Botany","Zoology","Climatology","Oceanography","Agriculture","Differential equations and dynamics","Economics"],
"Microbiology": ["Immunology","Digestive system","Medicine","Epidemiology and public health","Agriculture"],
"Botany": ["Agriculture","Climatology","Ecology"],
"Zoology": ["Skeletal system","Neuroscience","Anthropology"],
"Neuroscience": ["Nervous system","Psychology","Cognitive science","Artificial intelligence","Endocrine system","Philosophy"],
"Developmental biology": ["Reproductive system","Genetics","Evolutionary biology"],
"Immunology": ["Lymphatic and immune system","Medicine","Epidemiology and public health","Microbiology"],
"Skeletal system": ["Muscular system","Homeostasis","Engineering"],
"Muscular system": ["Nervous system","Cardiovascular system","Nutrition","Biochemistry"],
"Nervous system": ["Endocrine system","Homeostasis","Digestive system","Psychology"],
"Endocrine system": ["Homeostasis","Reproductive system","Digestive system","Urinary system"],
"Cardiovascular system": ["Respiratory system","Urinary system","Lymphatic and immune system","Homeostasis","Medicine"],
"Respiratory system": ["Homeostasis","Nutrition","Acoustics"],
"Digestive system": ["Nutrition","Urinary system","Microbiology"],
"Urinary system": ["Homeostasis","Medicine"],
"Reproductive system": ["Endocrine system","Developmental biology"],
"Integumentary system": ["Immunology","Homeostasis","Optics"],
"Lymphatic and immune system": ["Immunology","Cardiovascular system"],
"Homeostasis": ["Differential equations and dynamics","Medicine","Thermodynamics"],
"Geology": ["Planetary science","Oceanography","Climatology","Evolutionary biology","Materials science"],
"Meteorology": ["Climatology","Oceanography","Differential equations and dynamics","Statistics"],
"Climatology": ["Oceanography","Agriculture","Political science","Economics"],
"Oceanography": ["Ecology","Climatology","Fluid dynamics"],
"Planetary science": ["Astronomy","Climatology","Geology"],
"Astronomy": ["Optics","History","Astrophysics and cosmology"],
"Arithmetic and number theory": ["Algebra","Logic and set theory","Computer science","Discrete mathematics","Information theory"],
"Algebra": ["Linear algebra","Calculus","Geometry and trigonometry","Topology","Logic and set theory"],
"Geometry and trigonometry": ["Calculus","Topology","Linear algebra","Acoustics","Engineering"],
"Calculus": ["Differential equations and dynamics","Probability","Linear algebra","Statistics","Economics","Physical chemistry","Fluid dynamics","Electromagnetism"],
"Linear algebra": ["Artificial intelligence","Statistics","Computer science","Topology"],
"Probability": ["Statistics","Information theory","Quantum mechanics","Economics","Epidemiology and public health","Discrete mathematics"],
"Statistics": ["Psychology","Economics","Sociology","Medicine","Nutrition","Epidemiology and public health","Artificial intelligence","Genetics"],
"Logic and set theory": ["Philosophy","Computer science","Discrete mathematics","Topology"],
"Discrete mathematics": ["Computer science","Information theory","Artificial intelligence","Political science"],
"Differential equations and dynamics": ["Meteorology","Economics","Ecology","Cardiovascular system","Engineering","Topology"],
"Topology": ["Condensed matter physics","Astrophysics and cosmology","Artificial intelligence"],
"Computer science": ["Information theory","Artificial intelligence","Cognitive science","Engineering","Philosophy"],
"Information theory": ["Artificial intelligence","Linguistics","Genetics","Thermodynamics"],
"Artificial intelligence": ["Cognitive science","Linguistics","Psychology","Philosophy","Statistics"],
"Psychology": ["Cognitive science","Sociology","Economics","Medicine","Linguistics","Neuroscience"],
"Cognitive science": ["Linguistics","Philosophy","Neuroscience","Computer science"],
"Linguistics": ["Anthropology","History","Philosophy","Acoustics"],
"Economics": ["Sociology","Political science","History","Agriculture","Psychology"],
"Sociology": ["Anthropology","Political science","History","Epidemiology and public health"],
"Anthropology": ["History","Agriculture","Linguistics","Evolutionary biology"],
"Political science": ["History","Philosophy","Economics","Sociology"],
"History": ["Philosophy","Medicine","Agriculture","Astronomy"],
"Philosophy": ["Logic and set theory","Cognitive science","Political science","Neuroscience"],
"Medicine": ["Nutrition","Epidemiology and public health","Immunology","Cardiovascular system","Statistics","Nervous system"],
"Nutrition": ["Digestive system","Biochemistry","Agriculture","Epidemiology and public health","Muscular system"],
"Engineering": ["Materials science","Computer science","Fluid dynamics","Agriculture","Classical mechanics"],
"Agriculture": ["Botany","Ecology","Genetics","Economics","Climatology"],
"Epidemiology and public health": ["Statistics","Medicine","Sociology","Microbiology","Immunology"],
}
s = open('data.js').read()
names = re.findall(r'n: "([^"]+)"', s)
for n, links in L.items():
    assert n in names, 'unknown source ' + n
    for l in links: assert l in names, f'unknown link {l} from {n}'
    js = ', '.join('"%s"' % l for l in links)
    s, c = re.subn(r'(\{ d: "[^"]+", n: "%s",)' % re.escape(n), r'\1 r: [%s],' % js, s, count=1)
    assert c == 1, n
assert set(L) == set(names), set(names) - set(L)
s = s.replace("// shape: { d: domain, n: name,", "// shape: { d: domain, n: name, r: related field names (undirected; the graph is the union of both directions),")
open('data.js', 'w').write(s)
print('links', sum(len(v) for v in L.values()))
